# Generated by Django 4.2.7 on 2023-11-16 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='user',
        ),
        migrations.AddField(
            model_name='site',
            name='user_auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.userauth'),
            preserve_default=False,
        ),
    ]
